### PR TITLE
implements register,login,add,modify,delete,borrow,view API endpoints

### PR DESCRIPTION
**Pull request by TheSteelGuy**
**Introduction**
This PR adds most of the API endpoints for the hello-books app
**details**
the end points wiithin the app are:

- admin can log in

a logged in admin can:

- add book

- modify book

- delete book

- get books(view)
**registred user can :**

- log in

- borrow book

- view all books
also unittests are included,
_the endpoints were tested with postman_

### CODE REVIEW

**Review by geeeh — COMMENTED** [review]
- Why did you get rid of the READme?
- You do not need `GET` Verb for login.
- checkout difference between CONFLICT and BAD REQUEST status codes.
- Basically, check out all HTTP status codes. You are mixing them up.
-

**Comment by geeeh** [comment]
Also, make use of virtualenv. It will help with requirements. I don't think your project is using all those requirements.

**Comment by TheSteelGuy** [comment]
yeah thanks , i am actually using a virtual enviroment. Its just that i have been using it for quite  a while, perhaps i deleted it mistakenly. i will add it.

**Comment by TheSteelGuy** [comment]
i will change the request methods, i also noted that i wronged somewhere. Thanks for bringing it up it

**Pull request merged**
