### PR TITLE
[#156009821,#156008819, #156239810] implements models for the entities of the app

### PR DESCRIPTION
**Pull request by TheSteelGuy**
**Inrtroduction**

The PR is implements the related stories.
**details**
contains the app structurea and relatetad files such as:

- configaration file

- tests files

- Both views for the admin and users

- __init__ configaration files for the app

**How it works:**

- The classes.py files contains the modeling classes and releted methods for each class
which allow that class to prerform an action such ass adding abook

- The views are responsible for handling requests and intreacts to the classes for response.

### CODE REVIEW

**Comment by TheSteelGuy** [comment]
Please @erianfranky , @simiyu1 leave a comment

**Comment by TheSteelGuy** [comment]
@erianafranki

**Comment by TheSteelGuy** [comment]
@Erianafranky

**Comment by simiyu1** [comment]
This looks clean to me, apart from the hilarious spelling mistake ass instead of as in your second last sentence.

**Comment by benardokothe** [comment]
seems okay

**Comment by TheSteelGuy** [comment]
Ahahahahhaaaa, i have this tendency of not proofreading my texts, thanks brathe

**Comment by simiyu1** [comment]
Morning... I asked in slack about how you came up with the folder
structures brother

**Pull request merged**
